export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_ATTRIBUTE_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_ATTRIBUTE_SUCCESS = "GET_PRODUCT_ATTRIBUTE_SUCCESS";
export const GET_PRODUCT_ATTRIBUTE_FAIL = "GET_PRODUCT_ATTRIBUTE_FAIL";
